name: scuba_diving
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.18.0
  carousel_slider: ^4.2.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  http: ^1.4.0
  shared_preferences: ^2.0.15
  jwt_decoder: ^2.0.1
  flutter_rating_bar: ^4.0.1
  loading_animation_widget: ^1.2.1
  url_launcher: ^6.2.2
  font_awesome_flutter: ^10.7.0
  image_picker: ^1.0.4
  path: ^1.9.0

dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - images/
